### ISSUE TITLE
PHP 7.4.12 - Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters 

### ISSUE THREAD

**Issue by Xolof** [canax/htmlform#15]
När jag postar formuläret för att skapa användare får jag följande felmeddelande.

`Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /home/olof/dbwebb-kurser/ramverk1/me/kmom06/form/src/User/HTMLForm/CreateUserForm.php on line 244`

Lösningen är ju som det står i meddelandet, att byta plats på limmet och arrayen.

**Comment by mosbth** [comment]
Är det din egen kod som ger felet eller komemr det från modulen, eller från den scaffoldade koden?
Eller kanske från en artikel?

Tittar jag på felmeddelandet så låter det som det är din egen kod?

**Comment by Xolof** [comment]
Det är i CreateUserForm.php som jag scaffoldade fram enligt artikeln. Felmeddelandet kom när jag postade formuläret i webbläsaren.

För att förtydliga:
Jag tror det var rad 244 som gav felet.
`. implode( $this->form->value($name), ", ")`

Det fungerade när jag ändrade till
`. implode(", ", $this->form->value($name))`

**Comment by mosbth** [comment]
Japp, nu hittade jag det. Jag uppdaterade koden i anax/scaffold och nästa som genererar kommer slippa felet.
